# Load distro-specific variables
- include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- block:
  ## User configs
  - import_tasks: users/adi.yml

## desktop environments

  - include_tasks: desktop_environments/gnome/appearance.yml
    when: gnome is defined and gnome == true

  - include_tasks: desktop_environments/gnome/nautilus.yml
    when: gnome is defined and gnome == true

  - include_tasks: desktop_environments/gnome/packages.yml
    when: gnome is defined and gnome == true

  - include_tasks: desktop_environments/gnome/peripherals.yml
    when: gnome is defined and gnome == true

  - include_tasks: desktop_environments/gnome/shell_settings.yml
    when: gnome is defined and gnome == true

  - include_tasks: desktop_environments/gnome/terminal.yml
    when: gnome is defined and gnome == true

  ## system setup
  - import_tasks: system_setup/autofs.yml
  - import_tasks: system_setup/tweaks.yml

  ## install software
  - import_tasks: software/bitwarden.yml
  - import_tasks: software/codecs.yml
  - import_tasks: software/google_chrome.yml
  - import_tasks: software/keepassxc.yml
  - import_tasks: software/misc_packages.yml

  rescue:
    - set_fact: task_failed=true
