- name: software | install workstation distribution packages
  tags: packages,workstation-packages
  package:
    name:
      - "{{ cups_package }}"
      - dconf-editor
      - "{{ font_fira_mono_package }}"
      - "{{ font_hack_ttf_package }}"
      - "{{ font_inconsolata_package }}"
      - "{{ font_noto_emoji_package }}"
      - "{{ font_terminus_package }}"
      - gparted
      - transmission-gtk

- name: software | install system packages specific to debian and ubuntu
  tags: packages,system,system-packages,workstation-packages
  package:
    name:
      - synaptic
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]

- name: software | remove unneeded workstation packages on debian and ubuntu hosts
  tags: cleanup,packages,workstation-packages
  package:
    state: absent
    name:
      - libreoffice-base-core
      - libreoffice-calc
      - libreoffice-common
      - libreoffice-core
      - libreoffice-draw
      - libreoffice-gnome
      - libreoffice-gtk3
      - libreoffice-impress
      - libreoffice-math
      - libreoffice-writer
      - thunderbird*
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
