# Note: Some of these packages are disabled, they depend on tracker which is currently being disabled
- name: gnome | packages | install gnome packages
  tags: gnome,gnome-packages
  package:
    name:
      # - eog
      # - file-roller
      # - "{{ gdm_package }}"
      # - gedit
      - gnome-backgrounds
      # - gnome-books
      # - gnome-boxes
      - gnome-control-center
      - gnome-disk-utility
      # - gnome-documents
      - gnome-icon-theme
      # - gnome-music
      # - gnome-photos
      - gnome-power-manager
      # - gnome-remote-desktop
      - gnome-shell
      - gnome-shell-extensions
      - gnome-system-monitor
      - gnome-terminal
      # - gnome-todo
      - gnome-tweaks
      - nautilus

- name: gnome | packages | install flatpak support in gnome software
  tags: gnome,gnome-packages
  package:
    name:
    - gnome-software-plugin-flatpak
  when: ansible_distribution in ["Debian", "Ubuntu"]
