autofs_master_config: /etc/auto.master
autofs_nfs_config: /etc/auto.nfs
cryptsetup_package: cryptsetup-bin
cups_package: cups-daemon
font_fira_mono_package: fonts-firacode
font_hack_ttf_package: fonts-hack-ttf
font_inconsolata_package: fonts-inconsolata
font_noto_emoji_package: fonts-noto-color-emoji
font_terminus_package: xfonts-terminus
gdm_package: gdm3
gstreamer_libav_package: gstreamer1.0-libav
gstreamer_plugins_bad_package: gstreamer1.0-plugins-bad
hunspell_package: hunspell-en-us
hyphen_package: hyphen-en-us
jay_user_group: adi
libnotify_package: libnotify-bin
mpv_package: gnome-mpv
ssh_askpass_package: ssh-askpass-gnome
